[build.production]
  base = "content/2023"
  publish = "output"
  build = "env SITEURL=$URL make html"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[[redirects]]
  from = "/register"
  to = "https://sciwork.kktix.cc/events/sciworkconf-202312-hsinchu"
  force = true
